### ISSUE TITLE
Word of the day not available 

### ISSUE THREAD

**Issue by kyoforkshomebrews** [Sav22999/word-of-the-day#5]

**Comment by Sav22999** [comment]
Hi, thanks for the report.
I'm having some problems and I don't have enough time, for now, to add new words.
Sorry.

I'll add asap

**Comment by licaon-kter** [comment]
fyi https://gitlab.com/fdroid/fdroiddata/-/commit/75321f47aae4d4384bad45e3c953c7c6323a9f8c :(

**Comment by Sav22999** [comment]
@licaon-kter why this issue? The app doesn't use any external library and it's totally open-source 🤷‍♂️

**Comment by licaon-kter** [comment]
@Sav22999 the app does not work, for me

Is your server online?

**Comment by Sav22999** [comment]
@licaon-kter Yes, it's online. It's the same server of my website (saveriomorelli.com). Just there werren't any words, sorry. Try now and it should work 😄

**Comment by licaon-kter** [comment]
Mmmkay now :) https://gitlab.com/fdroid/fdroiddata/-/commit/9f907f7d75c855133cfa01a6e7e8faf7e8814acf

**Comment by Sav22999** [comment]
@licaon-kter Thanks!

I'm thinking to a new update for this app 😄
