### ISSUE TITLE
Add other languages?

### ISSUE THREAD

**Issue by Aphexus** [Sav22999/word-of-the-day#6]
What would be nice is if the word would give translations in different languages so one could learn how the word is said in many different languages all at once.

**Comment by Sav22999** [comment]
@Aphexus this is a great suggestion. Now the project is temporarily interrupted because I don't have any time to upload new words on my server. Sorry for the inconvenience, I'll insert new words asap and reenable the project

**Comment by Sav22999** [comment]
@Aphexus the project is back again, but only in English
