### ISSUE TITLE
History of Words Learned in past.

### ISSUE THREAD

**Issue by Jenish-1235** [Sav22999/word-of-the-day#8]
It would be great to have the history of the words that are learnt from app in a separate acitivity, which stores list of all words learnt in past, so user can revisit them in order to keep them retained in head.

**Comment by Sav22999** [comment]
@Jenish-1235 Hi, thanks for the suggestion.
It is a very interesting feature to add, you're right!

I'll add it to the to-do list for the future 😊

**Comment by Jenish-1235** [comment]
You can assign this issue to me, I would love to create it

**Comment by Jenish-1235** [comment]
Hello there, haven't listened from you in a while. Let me know if I can work on this feature ?

**Comment by Sav22999** [comment]
@Jenish-1235 Hi, sure, you can work on it

**Comment by Jenish-1235** [comment]
Thanks dude

**Comment by Jenish-1235** [comment]
Could you help out me with figuring out , why is app not getting new words, instead it shows server down.

**Comment by Sav22999** [comment]
I’m sorry about this inconvenience, I’ll see tomorrow. Sorry

––––
Saverio Morelli
